### PR TITLE
Prepare 0.2.6 release

### PR DESCRIPTION
**Pull request by jpichon**
Also update the README with tips on how to avoid the gotcha from last time until we automate all this.

### CODE REVIEW

**Review by fuzzball81 — APPROVED** [review]

**Comment by jpichon** [comment]
Looks like one of the travis jobs is hanging (integration, which is definitely not affected by this patch) so mergify can't do its thing. I'll force merge in the morning if this still hasn't gone through.

**Comment by jguiditta** [comment]
Just looked to see what is taking travis so long, and saw this message:
```
Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.
```
We should migrate this repo to use actions (as we have in others) asap so this doesn't impact PRs.

**Review by jguiditta — APPROVED** [review]
Looks good to me too

**Comment by jguiditta** [comment]
> Looks like one of the travis jobs is hanging (integration, which is definitely not affected by this patch) so mergify can't do its thing. I'll force merge in the morning if this still hasn't gone through.

I'll merge it for you this afternoon if travis doesn't unstick, so you don't have to self-merge.

**Comment by jpichon** [comment]
Perfect, thanks. I restarted the build, we'll see if the second run goes better. I'll do the work to move to github actions next week.

**Comment by fuzzball81** [comment]
Let's get this moved over to actions and off of travis. @jguiditta I think you had something setup on one of the other repos, is that something we can reuse here?

**Comment by jguiditta** [comment]
> Let's get this moved over to actions and off of travis. @jguiditta I think you had something setup on one of the other repos, is that something we can reuse here?

Yes, we have moved flask-container-scaffold and toolchest over so far. @jpichon if you have any issues with the conversion or run tight on time, I am happy to help.

**Comment by jpichon** [comment]
Thanks, I will definitely look at what we have already! I think I did that for the rtls skeleton as well so it should be fine. Will upload the new git_wrapper release now.

**Pull request merged**
